name: Build try-runtime base image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ensure tooling is installed
        run: apt-get install --yes curl jq
      - name: Fetch try-runtime latest version
        id: version
        run: |
          VERSION=`curl https://api.github.com/repos/paritytech/try-runtime-cli/releases/latest | jq -r .tag_name`
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/nodlecode/try-runtime-cli
          tags: |
            type=raw,value=${{ steps.version.outputs.VERSION }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: './base/Dockerfile'
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=${{ steps.version.outputs.VERSION }}
